python3 hir/ArrayAccess.py || exit
python3 hir/ArraySpecifier.py || exit
python3 hir/AssignmentExpression.py || exit
python3 hir/BinaryExpression.py || exit
python3 hir/BreadthFirstIterator.py || exit
python3 hir/BreakStatement.py || exit
python3 hir/Case.py || exit
python3 hir/CharLiteral.py || exit
python3 hir/CompoundStatement.py || exit
python3 hir/ConditionalExpression.py || exit
python3 hir/ContinueStatement.py || exit
python3 hir/Declaration.py || exit
python3 hir/DeclarationStatement.py || exit
python3 hir/Declarator.py || exit
python3 hir/Default.py || exit
python3 hir/Digrapher.py || exit
python3 hir/DoLoop.py || exit
python3 hir/Expression.py || exit
python3 hir/ExpressionStatement.py || exit
python3 hir/FloatLiteral.py || exit
python3 hir/ForLoop.py || exit
python3 hir/FunctionCall.py || exit
python3 hir/IDExpression.py || exit
python3 hir/Identifier.py || exit
python3 hir/IfStatement.py || exit
python3 hir/Imports.py || exit
python3 hir/IntegerLiteral.py || exit
python3 hir/Keyword.py || exit
python3 hir/Literal.py || exit
python3 hir/Loop.py || exit
python3 hir/Operator.py || exit
python3 hir/ParameterDeclarator.py || exit
python3 hir/Procedure.py || exit
python3 hir/ProcedureDeclarator.py || exit
python3 hir/ReturnStatement.py || exit
python3 hir/Specifier.py || exit
python3 hir/Statement.py || exit
python3 hir/SwitchStatement.py || exit
python3 hir/SymbolTable.py || exit
python3 hir/Traversable.py || exit
python3 hir/UnaryExpression.py || exit
python3 hir/VariableDeclaration.py || exit
python3 hir/VariableDeclarator.py || exit
python3 hir/WhileLoop.py || exit
python3 hir/__init__.py || exit
python3 hir/bfs.py || exit
python3 hir/import_all.py || exit
python3 hir/odict.py || exit
